// Replace these values when the final photos, date, music and RSVP endpoint are ready.
const settings={eventDate:'2026-08-08T17:00:00+05:00',musicUrl:'',rsvpEndpoint:''};
const calendar=document.getElementById('calendar');
for(let i=0;i<5;i++)calendar.append(document.createElement('span'));
for(let day=1;day<=31;day++){const cell=document.createElement('span');cell.textContent=day;if(day===8){cell.className='selected';cell.setAttribute('aria-label','8 августа — день торжества')}calendar.append(cell)}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if('IntersectionObserver'in window&&!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('waiting');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('waiting');observer.observe(el)}});window.addEventListener('pagehide',()=>document.querySelectorAll('.waiting').forEach(el=>el.classList.remove('waiting')))}
function updateCountdown(){const left=Math.max(0,new Date(settings.eventDate).getTime()-Date.now());const units=[Math.floor(left/86400000),Math.floor(left/3600000)%24,Math.floor(left/60000)%60,Math.floor(left/1000)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(units[i]).padStart(2,'0'));return left}
if(updateCountdown()>0)setInterval(updateCountdown,1000);
const audio=document.getElementById('audio'),music=document.getElementById('music'),notice=document.getElementById('music-status');let toastTimer;
function toast(text){notice.textContent=text;notice.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>notice.classList.remove('show'),4500)}
if(settings.musicUrl)audio.src=settings.musicUrl;
music.addEventListener('click',async()=>{if(!settings.musicUrl){toast('Здесь будет ваша музыка. Пришлите выбранную композицию.');return}if(audio.paused){try{await audio.play();music.setAttribute('aria-pressed','true');music.setAttribute('aria-label','Выключить музыку')}catch{toast('Не удалось включить музыку. Попробуйте ещё раз.')}}else{audio.pause();music.setAttribute('aria-pressed','false');music.setAttribute('aria-label','Включить музыку')}});
document.getElementById('rsvp-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=document.getElementById('form-status'),name=form.elements.name.value.trim();if(!name){form.elements.name.setCustomValidity('Пожалуйста, укажите имя');form.elements.name.reportValidity();return}if(!settings.rsvpEndpoint){status.textContent='Это предпросмотр. Ваш ответ не отправлен: приём заявок пока не подключён.';return}const button=form.querySelector('button');button.disabled=true;status.textContent='Отправляем…';try{const response=await fetch(settings.rsvpEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,attendance:form.elements.attendance.value})});if(!response.ok)throw Error('Failed');status.textContent='Спасибо! Ваш ответ принят.';form.reset()}catch{status.textContent='Ответ не отправлен. Попробуйте ещё раз.'}finally{button.disabled=false}});
document.getElementById('guest-name').addEventListener('input',e=>e.target.setCustomValidity(''));
